create table tb_compras (
        id bigint generated by default as identity,
        comprador varchar(255),
        data date,
        parcelas_pagas integer,
        produto varchar(255),
        total_parcelas integer,
        valor float,
        vendedor varchar(255),
        cartao_id bigint,
        primary key (id)
        );
create table tb_cartoes (
           id bigint generated by default as identity,
           nome_cartao varchar(255),
           primary key (id)
           );

alter table tb_compras
             add constraint FK46tewxi64d5cvh9r7o4w9397h
             foreign key (cartao_id)
             references tb_cartoes;