CREATE TABLE IF NOT EXISTS user_permission(
  id_user bigint generated by default as identity not null,
  id_permission bigint generated by default as identity not null,
  PRIMARY KEY (id_user,id_permission),
  CONSTRAINT fk_user_permission FOREIGN KEY (id_user) REFERENCES users (id),
  CONSTRAINT fk_user_permission_permission FOREIGN KEY (id_permission) REFERENCES permission (id)
);